name: Backend CI

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'
  pull_request:
    branches: [dev]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'  # Or any version you're using

      - name: Install dependencies with npm
        run: npm ci

      - name: Run the application (start server)
        run: npm start  # Make sure the "start" script exists in package.json
